function expopt = experimentParamsYoung()

figureCoh = 10;
toneCompHigh = 20-figureCoh;
toneCompLow = toneCompHigh+5;


expopt = struct( ...
    'figureCoh', figureCoh, ...
    'toneCompHigh', toneCompHigh, ...
    'toneCompLow', toneCompLow, ...
    'stepSizeMin', -10, ...
    'stepSizeMax', 10, ...
    'stepSizeStep', 1);
        
end
        