function expopt = experimentParamsYoung()

figureCoh = 10;
toneCompHigh = 20-figureCoh;
toneCompLow = toneCompHigh+5;


% TODO min step size
expopt = struct( ...
    'figureCoh', figureCoh, ...
    'toneCompHigh', toneCompHigh, ...
    'toneCompLow', toneCompLow, ...
    'stepSizeMin', 60, ...
    'stepSizeMax', 100, ...
    'stepSizeStep', 1);
        
end
        